// Generated by CoffeeScript 1.3.3
(function() {

  this.CallbackManager = {
    cbs_: new Array(),
    register_callback: function(cb) {
      this.cbs_.push(cb);
      return this.cbs_.length - 1;
    },
    get_callback: function(index) {
      return this.cbs_[index];
    }
  };

}).call(this);
